//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentYulia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentYulia()
        {
            this.OrderShitikova = new HashSet<OrderShitikova>();
        }
    
        public int ID { get; set; }
        public int IDEmloyee { get; set; }
        public int IDMedicalService { get; set; }
        public System.DateTime DateService { get; set; }
    
        public virtual EmployeeShitikova EmployeeShitikova { get; set; }
        public virtual MedicalServiceShitikova MedicalServiceShitikova { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderShitikova> OrderShitikova { get; set; }
    }
}
