//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeShitikova
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeShitikova()
        {
            this.AppointmentYulias = new HashSet<AppointmentYulia>();
        }
    
        public int ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string MName { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public string Phone { get; set; }
        public int IDDepartment { get; set; }
        public int IDPost { get; set; }
        public int IDGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentYulia> AppointmentYulias { get; set; }
        public virtual DepartmentShitikova DepartmentShitikova { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual PostShitikova PostShitikova { get; set; }
    }
}
