//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalService3
    {
        public string TitleService { get; set; }
        public string ФИО { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime DateService { get; set; }
        public int Duration { get; set; }
    }
}
