//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagOfClient
    {
        public int ID { get; set; }
        public string NameTag { get; set; }
        public int IDClient { get; set; }
    
        public virtual PatientShitikova PatientShitikova { get; set; }
    }
}
